# Exercise 01.1 Intro to ML - Numpy Recap

## Pedagogy

This notebook contains both theoretical explanations and executable cells to execute your code.

When you see the <span style="color:red">**[TBC]**</span> (To Be Completed) sign, it means that you need to perform an action else besides executing the cells of code that already exist. These actions can be:
- Complete the code with proper comments
- Respond to a question
- Write an analysis
- etc.

## Part 1. NumPy ultra-quick tutorial

[Numpy](https://numpy.org/doc/stable/index.html) is a Python library for creating and manipulating matrices, the main data structure used by ML algorithms. [Matrices](https://en.wikipedia.org/wiki/Matrix_(mathematics)) are mathematical objects used to store values in rows and columns.

Python calls matrices *lists*, NumPy calls them *arrays*.

This notebook is not an exhaustive tutorial on NumPy. Rather, the purpose of this notebook is to let you review the knowledge about NumPy you learned in the Python Bootcamp course, and set up python, anaconda, jupyter notebook and other tools for subsequent courses.

### Import NumPy library

Run the following code cell to import the NumPy library.

In [1]:
# import the NumPy library
import numpy as np

### Populate arrays with specific numbers

Call `np.array` to create a NumPy array with you own hand-picked values. For example, the following call to `np.array` creates an 8-element array.

In [2]:
# create an 8-element array
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


You can also use `np.array` to create a two-dimensional array. To do that, specify an extra layer of square brackets. For example, the following call creates a 3$\times$2 array:

In [3]:
# create a two-dimensional array
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


To populate an array with all zeros, call `np.zeros`.

In [4]:
# create an array with all zeros
all_zero_array = np.zeros(8)
print(all_zero_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


To populate an array with all ones, call `np.ones`.

In [5]:
# create an array with all ones
all_one_array = np.ones((3,2))
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100.

In [6]:
# create a 6-element array with random integers between 50 and 100
random_integers_between_50_and_100 = np.random.randint(low = 50, high = 101, size = (6))
print(random_integers_between_50_and_100)

[58 77 64 62 63 93]


Note that the highest generated integer will be less than the `high` argument. More explanations about `np.random.randint` can be found in the official documentation: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy.random.randint

To create random floating-point values between 0.0 and 1.0, call `np.random.random`. For example:

In [7]:
# create an array with random floating-point values between 0.0 and 1.0
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.16362705 0.44621064 0.66003978 0.19589931 0.89320691 0.03507113]


### Mathematical operations on NumPy operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell:

In [8]:
# add 2.0 to every item in the array
random_floats_between_2_and_3 = 2.0 + random_floats_between_0_and_1
print(random_floats_between_2_and_3)

[2.16362705 2.44621064 2.66003978 2.19589931 2.89320691 2.03507113]


The following operation also relies on broadcasting to multiply each item in an array by 3:

In [9]:
# multipy each item in the array by 3
random_integers_between_150_and_300 = 3 * random_integers_between_50_and_100
print(random_integers_between_150_and_300)

[174 231 192 186 189 279]


## Part 2. Hands-on exercises

Please complete the following two exercises.

### Task 1. Create a linear dataset

<span style="color:red">**[TBC]**</span>: Your goal is to create a simple dataset consisting of a single feature and a label as follows:
1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`
2. Assign 15 values to a NumPy array named `label` such that: label = 3 $\times$ feature + 4
3. Print the created `feature` and `label`

For example, the first value for `label` should be:

3 $\times$ 6 + 4 = 22

In [12]:
# [TBC] complete your code here with proper comments
feature = np.random.randint(low = 6, high = 21, size = (15))
print(feature)

label = 3 * feature + 4
print(label)


[13 14  6 16 15 20  8 19 13  8 11 17 18 14 11]
[43 46 22 52 49 64 28 61 43 28 37 55 58 46 37]


### Task 2. Add some noise to the dataset

<span style="color:red">**[TBC]**</span>: To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a different random floating-point value between -2 and +2.

In [19]:
# [TBC] complete your code here with proper comments
float = np.random.random([15])
label = label + float
label

array([45.33363897, 47.11202953, 24.31468808, 53.3525569 , 51.17527368,
       65.72613684, 29.00647157, 64.0236584 , 44.48590246, 29.4151612 ,
       38.92561537, 56.46365422, 61.09719424, 49.39821231, 38.20483179])